############################################
## Validator Database URL Secret
############################################
{{- if not .Values.databaseUrlSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}-database-url-secret
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $dbUrl := $.Values.databaseUrl }}
  {{- if kindIs "slice" $dbUrl }}
  {{- $dbUrl = ($dbUrl | join ",") }}
  {{- end }}
  database-url: {{ $dbUrl | b64enc | quote }}
{{- end }}
