############################################
## Validator Signing Key Secret
############################################
{{- if not .Values.signingKeySecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}-signing-key-secret
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- include "validator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $signingKey := $.Values.signingKey }}
  {{- $signingKey = ($signingKey | join ",") }}
  signing-key: {{ $signingKey | b64enc | quote }}
{{- end }}
