apiVersion: v2
name: validator
description: A Helm chart for the Flashnet validator

type: application

version: 0.0.1

appVersion: "0.0.1"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
