---
apiVersion: v2
name: validator
description: A Helm chart for the Flashnet validator
home: https://flashnet.xyz/
keywords:
  - flashnet
  - settlement
  - validator
  - nitro

type: application

version: 0.2.0

appVersion: "0.0.1"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
