# Provide a name to substitute for the full names of resources
fullnameOverride: ""

# Provide a name to substitute for the name of the chart
nameOverride: ""

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: "latest"

command:
  enabled: true
  data:
    - "/bin/sh"
    - "-c"
    - "/app/flashnet-validator"

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 50059

databaseUrl: []
databaseUrlSecretName: ~

config:
  grpcBindAddress: "0.0.0.0:50059"
  signingKey: []
  runningAuthority: "<YOUR_RUNNING_AUTHORITY>"
  teeCryptoModulePublicKey: []
  validatorId: []  # Validator UUIDs from database registry (comma-separated in env)

env:
  - name: RUST_LOG
    value: "info"

metrics:
  datadog:
    enabled: true
    env: production
