apiVersion: v1
kind: Service
metadata:
  name: {{ include "rwconsole.fullname" . }}
  labels:
    {{- include "rwconsole.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: webui
      port: {{ .Values.rwconsole.port }}
    - name: metrics
      port: {{ .Values.metrics.port }}
    {{- if .Values.debug.enabled }}
    - name: debug
      port: {{ .Values.debug.port }}
    {{- end }}
  selector:
    {{- include "rwconsole.selectorLabels" . | nindent 4 }}
