apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator.fullname" . }}-headless
  labels:
    {{- include "validator.labels" . | nindent 4 }}
    {{- include "validator.fullname" . }}-headless: "true"
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "validator.selectorLabels" . | nindent 4 }}
