apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
    {{- if .Values.metrics.datadog.enabled }}
    admission.datadoghq.com/enabled: "true"
    tags.datadoghq.com/env: {{ .Values.metrics.datadog.env }}
    tags.datadoghq.com/service: {{ include "validator.fullname" . }}
    tags.datadoghq.com/version: {{ .Chart.AppVersion }}
    {{- else }}
    admission.datadoghq.com/enabled: "false"
    {{- end }}
    {{- include "validator.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.metrics.datadog.enabled }}
    ad.datadoghq.com/exclude: "false"
    {{- else }}
    ad.datadoghq.com/exclude: "true"
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- if $.Values.metrics.datadog.enabled }}
        ad.datadoghq.com/exclude: "false"
        {{- else }}
        ad.datadoghq.com/exclude: "true"
        {{- end }}
      {{- end }}
      labels:
        {{- include "validator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.metrics.datadog.enabled }}
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: {{ .Values.metrics.datadog.env }}
        tags.datadoghq.com/service: {{ include "validator.fullname" . }}
        tags.datadoghq.com/version: {{ .Chart.AppVersion }}
        {{- else }}
        admission.datadoghq.com/enabled: "false"
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers.enabled }}
      initContainers:
      - name: init-wait-redis
        image: alpine:3.16.0
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 $REDIS_HOST 6379 && exit 0 || sleep 3; done; exit 1"]
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
        resources:
            limits:
              cpu: 20m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 10Mi
        env:
          - name: REDIS_HOST
            value: {{ .Values.initContainers.redisHost | default "validator-1-redis-master" }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{ if .Values.command.enabled }}
          command: {{ toYaml .Values.command.data | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- if $.Values.metrics.datadog.enabled }}
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION 
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            {{- end }}
            - name: INDEX
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['apps.kubernetes.io/pod-index']"
            {{- toYaml . | nindent 12 }}
            - name: GRPC_BIND_ADDRESS
              value: {{ $.Values.config.grpcBindAddress }}
            - name: VALIDATOR_REDIS_CONNECTION_URL
              value: {{ $.Values.config.validatorRedisConnectionUrl }}
            - name: SIGNING_KEY
              value: {{ range $i, $e := $.Values.config.signingKey }}{{ if $i }},{{ end }}{{ $e }}{{ end }}
            - name: VALIDATOR_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['apps.kubernetes.io/pod-index']"
            - name: RUNNING_AUTHORITY
              value: {{ $.Values.config.runningAuthority }}
            - name: TEE_CRYPTO_MODULE_PUBLIC_KEY
              value: {{ range $i, $e := $.Values.config.teeCryptoModulePublicKey }}{{ if $i }},{{ end }}{{ $e }}{{ end }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
