apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
    {{- include "validator.datadog.labels" . | nindent 4 }}
    {{- include "validator.labels" . | nindent 4 }}
  annotations:
    {{- include "validator.datadog.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
{{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- include "validator.datadog.annotations" . | nindent 8 }}
{{- end }}
      labels:
        {{- include "validator.labels" . | nindent 8 }}
{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
{{- end }}
        {{- include "validator.datadog.labels" . | nindent 8 }}
    spec:
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
{{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
{{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
{{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{ if .Values.command.enabled }}
          command: {{ toYaml .Values.command.data | nindent 12 }}
{{- end }}
{{- with .Values.env }}
          env:
  {{- if $.Values.metrics.datadog.enabled }}
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION 
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
  {{- end }}
            - name: INDEX
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['apps.kubernetes.io/pod-index']"
            {{- toYaml . | nindent 12 }}
            - name: GRPC_BIND_ADDRESS
              value: {{ $.Values.config.grpcBindAddress }}
            - name: SIGNING_KEY
              value: {{ range $i, $e := $.Values.config.signingKey }}{{ if $i }},{{ end }}{{ $e }}{{ end }}
            - name: VALIDATOR_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['apps.kubernetes.io/pod-index']"
            - name: RUNNING_AUTHORITY
              value: {{ $.Values.config.runningAuthority }}
            - name: TEE_CRYPTO_MODULE_PUBLIC_KEY
              value: {{ range $i, $e := $.Values.config.teeCryptoModulePublicKey }}{{ if $i }},{{ end }}{{ $e }}{{ end }}
            - name: VALIDATOR_ID
              value: {{ range $i, $e := $.Values.config.validatorId }}{{ if $i }},{{ end }}{{ $e }}{{ end }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "database_url_secret" $ }}
                  key: database-url
{{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
{{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
